- name: Check if pam-config did a previous run
  command: "egrep '^auth.*pam_sss.so' /etc/pam.d/common-auth"
  register: pamConfig_run
  changed_when: false
  ignore_errors: true

- name: Configure PAM to use SSSD for auth
  command: pam-auth-update --package --enable sss --enable mkhomedir
  when: pamConfig_run.rc != 0