- name: Check if pam-config did a previous run
  command: "egrep '^auth.*sufficient.*pam_sss.so' /etc/pam.d/system-auth"
  register: pamConfig_run
  changed_when: false
  ignore_errors: true

- name: Configure PAM to use SSSD for auth
  command: authconfig --update --enablesssd --enablesssdauth --enablemkhomedir
  when: pamConfig_run.rc != 0

- name: Ensure oddjobd for mkhomedir is started and enabled on boot
  service:
    name=oddjobd
    state=started
    enabled=yes
